TWEAK_NAME = Juin JuinCanvasHelper
Juin_FILES = Juin.xm MarqueeLabel.m
Juin_CFLAGS = -fobjc-arc
Juin_FRAMEWORKS = UIKit CoreText AVFoundation
Juin_PRIVATE_FRAMEWORKS = MediaRemote AppSupport
Juin_EXTRA_FRAMEWORKS = Cephei
Juin_LIBRARIES = rocketbootstrap

JuinCanvasHelper_FILES = JuinCanvasHelper.xm
JuinCanvasHelper_CFLAGS = -fobjc-arc
JuinCanvasHelper_FRAMEWORKS = UIKit

ADDITIONAL_CFLAGS += -DTHEOS_LEAN_AND_MEAN

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk